services:
  backend:
    image: antihub-backend:local
    build:
      context: ./AntiHub-Backend
      dockerfile: Dockerfile

  plugin:
    image: antihub-plugin:local
    build:
      context: ./AntiHub-plugin
      dockerfile: Dockerfile

